name: Tests
on: ["push", "pull_request"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn jest --coverage --collectCoverageFrom=src/**/*.{ts,tsx}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}